### ISSUE TITLE
Timeline and project ideas about CNCF GSoC

### ISSUE THREAD

**Issue by resouer** [cncf/soc#1]
Wow! Excited to have CNCF GSoC 2017!

Here's something I am not fully aware of:

1. Will all the ideas listed in [idea doc](https://docs.google.com/spreadsheets/d/1Dg8LhFt4ky-z1Fg16BNLd9m1tue3QnAHeCc9MPmUuDg/edit#gid=0) be reviewed by GSoC, and then pick out the final ideas? Or, these are already final ideas?

2. What's the timeline when final ideas are ready so student can start to participate?

3. How to apply as mentor? For example, feiskyer (the approver of remote CRI) & me (reviewer of sig-node) are interested to mentor Containerd CRI, we have updated the idea doc, is it enough?

**Comment by caniszczyk** [comment]
1) these will be the list of final ideas, students have an option of submitting ideas but we only support ideas that have a full time mentoring assigned

2) https://developers.google.com/open-source/gsoc/timeline

3) first off, just add your idea + sign up as a mentor via the google sheet listed in #1, if CNCF gets accepted as a GSOC org on Feb 27th, you will then sign up as an official mentor on the GSOC site

**Comment by resouer** [comment]
Thanks, my questions are all well answered. Since I've added my info in google sheet listed in #1, let's close this issue.
