### ISSUE TITLE
Contributing to project: Develop a set of Jupyter Notebooks for the Python Client

### ISSUE THREAD

**Issue by shrenikjain38** [cncf/soc#10]
Hi,
I am interested in contributing to project : "Develop a set of Jupyter Notebooks for the Python Client" and have experience working with docker containers and clusters(kubernetes and swarm). Can someone guide for initial contributions to the project.

Thanks,
Shrenik Jain

**Comment by caniszczyk** [comment]
Hey @shrenikjain38, you're best bet is to reach out to @sebgoa and this issue:

https://github.com/kubernetes-incubator/client-python/issues/127
