### ISSUE TITLE
Ambiguity in the Community Bridge timeline

### ISSUE THREAD

**Issue by palash25** [cncf/soc#100]
The current timeline goes like this

```
    - December 5 2019 - December 15 2019: applications opened
    - December 16 2019: 5 projects/slots are announced by CNCF
    - December 16 2019 - March 16 2020: coding
    - March 20 2020: results announced
```

This doesn't mention when the selected students are announced for each project. And I am assuming that the Dec-March coding period refers to the project implementation rather than the period for submitting beginner patches for the projects in order to get selected. Can you clear this up @idvoretskyi ?

Also the 5 Dec to 15 Dec application period is it just open for project mentors or also for students. This timeline never mentions when should the student start working on their projects.

**Comment by idvoretskyi** [comment]
> This doesn't mention when the selected students are announced for each project. 

December 16 2019.

> And I am assuming that the Dec-March coding period refers to the project implementation rather than the period for submitting beginner patches for the projects in order to get selected.

It refers to the actual work on the project.

> This timeline never mentions when should the student start working on their projects.

December 16 is the start date.

**Comment by palash25** [comment]
So the students can start reaching out to the mentors right now?

**Comment by idvoretskyi** [comment]
> So the students can start reaching out to the mentors right now?

That's correct.

**Comment by idvoretskyi** [comment]
Details updated, thanks @palash25 - https://github.com/cncf/soc/commit/9fc38db7c4057a9106bbeb5a1a6f97351dbad811.
