### ISSUE TITLE
Add IRC Channel to connect with community

### ISSUE THREAD

**Issue by khyatisoneji** [cncf/soc#106]
Can we please add links to IRC channel in the project idea along with mentor information?

This would be very helpful to directly go to IRC channel and ask questions to the community.

**Comment by nikhita** [comment]
> Can we please add links to IRC channel in the project idea

Most CNCF projects have their own communication means. For example, Kubernetes has it's own slack instance (https://slack.k8s.io/). https://www.cncf.io/projects/ contains info about communication methods for all projects.

For broad CNCF related discussions, you can also join the CNCF slack at https://slack.cncf.io/. :)

> along with mentor information

Mentors are listed along with the project idea, you should be able to ping them directly once you join the projects' slack.

**Comment by nikhita** [comment]
Closing, feel free to comment here if you have any more questions about this.
