### ISSUE TITLE
Add containerd+CRI ideas

### ISSUE THREAD

**Issue by resouer** [cncf/soc#14]
This idea was originally added by @thockin in [doc](https://docs.google.com/spreadsheets/u/1/d/1Dg8LhFt4ky-z1Fg16BNLd9m1tue3QnAHeCc9MPmUuDg/edit#gid=0)

Now it's missing, and I just hope it come back.

**Comment by caniszczyk** [comment]
Hey @resouer just issue a pull request.

Make sure the idea has a mentor + link to github issue + desc

**Comment by resouer** [comment]
Sure, thank you for reminding!
