### ISSUE TITLE
Looking for another umbrella organization for GSOC2020, OpenWRT PPA with Kubernetes

### ISSUE THREAD

**Issue by zoobab** [cncf/soc#146]
Hi,

Freifunk was not selected as an GSOC2020 org, could you consider recycling this project of PPA for OpenWRT:

https://github.com/freifunk/projects.freifunk.net-contents/blob/master/collections/_projects/openwrt_ppa.md

Best regards,

**Comment by nikhita** [comment]
@zoobab Sorry for the late response. Unfortunately, we require that all GSoC projects be upstream CNCF projects. Given that this is a project which uses Kubernetes but is not an upstream project, we would not be able to take it on. :(
