### ISSUE TITLE
Timeline and Project Ideas for CNCF GCI

### ISSUE THREAD

**Issue by amitkumarj441** [cncf/soc#21]
Google has announced Google Code-in 2017 [program](http://opensource.googleblog.com/2017/09/announcing-google-code-in-2017.html)

1. Find Google Code-in timeline [here](https://developers.google.com/open-source/gci/timeline).
2. Tasks are categorized as:
    - Code
    - Documentation/Training
    - Outreach/Research
    - QA or UI/UX

@caniszczyk We need to gather tasks(relevant for GCI) and add it on google sheet to get ready for applying CNCF as GCI orgs.

**Comment by caniszczyk** [comment]
@amitkumarj441 can you reach out to Paris parispittman@google.com and see if there's interest in the Kubernetes community to do GCI. I don't have the bandwidth right now to have CNCF go full in, but if you are willing to help Paris with some GCI tasks, that would be a good start.

**Comment by amitkumarj441** [comment]
@caniszczyk I'll reach out to Paris asking for the interest and yes, I'm always up to help Paris with few tasks.

Thanks for the suggestion :grin:

**Comment by nikhita** [comment]
I think this can be closed now. GCI 2017 is over.
