### ISSUE TITLE
Application draft scheme for GSoC 2018

### ISSUE THREAD

**Issue by salvacorts** [cncf/soc#43]
There is no information about which information should we include on the draft to be submitted on the GSoC platform. May you add some information about it?
I would love to contribute on some projects this summer with you!!

**Comment by nikhita** [comment]
@salvacorts It's awesome that you would like contribute to CNCF projects, welcome!

We don't officially enforce an application template for GSoC. You are free to create the application the way you'd like. :) However, I'd suggest to reach out to the mentor for the project you are applying to and discuss the application with them before hashing it out completely.

In general, following points are good to cover:

- How you intend to solve the problem at hand/project.
- A timeline listing the milestones and deliverables for your project. Make sure you keep these realistic.
- If you will have any other commitments during the gsoc period, please mention them. Also mention if this would affect your work and the number of hours you can work on the project.
- How you intend to communicate your progress periodically (daily log/weekly log/blogposts, etc are good choices). Note: This is completely optional and depends on how you and your mentor work.
- Your past contributions to the project, if any.
- A little bit of background (academic, work experience) about yourself and general information (name, github id, slack/irc nick, timezone, etc).
- Why you chose this project.

**Comment by nikhita** [comment]
I have received numerous questions about how to write an application recently. I'm wondering if it would be better if we had a suggested template. Most organizations in GSoC do.

I'm pretty sure we don't "need" a template but I think it's easier and a "nice-to-have".  If it makes sense, I can create a PR about this.

@Gouthamve @sttts @caniszczyk @idvoretskyi thoughts?

**Comment by Gouthamve** [comment]
What I do to those approaching Prometheus community is link to my proposal while also some blog posts that helped me write my proposal. We could do the same, I guess. 

I like this one: http://teom.org/blog/kde/how-to-write-a-kick-ass-proposal-for-google-summer-of-code/

**Comment by nikhita** [comment]
@Gouthamve +1.

So something like "tips to write your proposal"? It could include some general advice (we can hash it out later if we need this) and a bunch of links to such blog posts.

**Comment by Gouthamve** [comment]
Yep, and also one or two previous proposals. I've seen GDB and couple of
other orgs do that.

**Comment by idvoretskyi** [comment]
+1. @nikhita please, go ahead

**Comment by nikhita** [comment]
@Gouthamve Can you share the link to your proposal? Will add it in.

**Comment by Gouthamve** [comment]
Sorry for not providing it earlier:
https://docs.google.com/document/d/1_kqdLrzF3PF7ycLHc9GRgX-_imBfupSuMFidseULWB8/edit

**Comment by nikhita** [comment]
I never got a chance to get it in for last year. I'm going to reopen this because I'd like to get this in for the next gsoc session.

**Comment by idvoretskyi** [comment]
Closing this for now. Will open another one for 2019, once the program will be officially started.

**Comment by idvoretskyi** [comment]
@caniszczyk it's scheduled for today.
