### ISSUE TITLE
Information about selection process for proposals

### ISSUE THREAD

**Issue by jbw976** [cncf/soc#45]
Should the README.md be updated with information about how the CNCF, as a mentoring organization for GSoC, will be performing the selection process on submitted proposals?  In particular, I'm curious about the following:
* Will the mentors for each project be responsible for reviewing proposals for their project?  Or will the CNCF be the only reviewers?
* Is there a limited number of proposals that can be accepted for the whole CNCF organization? Is there a limit per project?

Apologies if an issue isn't appropriate for tracking this information or if I missed this info in what's already published. Thanks!

**Comment by nikhita** [comment]
> Will the mentors for each project be responsible for reviewing proposals for their project?

Yes.

> Or will the CNCF be the only reviewers?

The organization admins are from CNCF. They can review the proposals as well, but mentors are responsible for it.

> Is there a limited number of proposals that can be accepted for the whole CNCF organization?

Yes, Google allots slots to organizations. Slots are the number of projects that can be accepted for gsoc.
https://developers.google.com/open-source/gsoc/help/slot-allocation

> Is there a limit per project?

@caniszczyk?

**Comment by jbw976** [comment]
Thanks @nikhita!  Is there a link for where proposals for our specific project are ready to be reviewed? or how to we find them?

**Comment by caniszczyk** [comment]
re: limit per project, we make a call based on the list of quality submissions, in the past, we have tried to give each CNCF project 1 slot (if they had a qualified proposal), but we leave this to judgement of CNCF staff

**Comment by caniszczyk** [comment]
@jbw976 you should have been invited to summerofcode.withgoogle.com/dashboard/ under the CNCF GSOC organization, if you haven't @idvoretskyi can invite you if you give him your email

**Comment by idvoretskyi** [comment]
@jbw976 please, email me to "ihor at cncf.io" with the preferred email; I'll check if you are invited, otherwise I'll invite you.

**Comment by nikhita** [comment]
Closing since this is resolved. Please reopen if there are any further issues.
