### ISSUE TITLE
Plan GSoC participation for 2020

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/soc#98]
GSoC 2019 is done - https://www.cncf.io/blog/2019/08/23/cncf-joins-google-summer-of-code-2019-with-17-interns-projects-for-containerd-coredns-kubernetes-opa-prometheus-rook-and-more/.

This is a placeholder issue to start GSoC 2020 planning.

/cc @caniszczyk

**Comment by davidcode00** [comment]
Hi @idvoretskyi  I am S. Krishna, undergrad at IIIT Delhi and interested in participating GSOC.  I have a prior interest in machine learning and it's applications. Please can you give some advice to help me getting started. Thanks :).

**Comment by idvoretskyi** [comment]
GSoC 2020 planning will start in January.

Please stay tuned.

**Comment by kumaran-14** [comment]
Hey. I'm Kumaran from India. I'm interested in participating in GSoC'20 and contributing to cncf. Could you help me in getting started?
Thanks in advance.

**Comment by caniszczyk** [comment]
@idvoretskyi can you create a file for 2020.md that people can start submitting ideas to

**Comment by idvoretskyi** [comment]
Sure, no problem!

**Comment by smishra997** [comment]
@idvoretskyi I would also like to start contributing for GSOC 2020, I am experienced in Full Stack Development as well as in Machine Learning too, so could you do as @caniszczyk said and we would start contributing as early as possible and probably try to do something good.

**Comment by idvoretskyi** [comment]
@caniszczyk we have this section in the README - https://github.com/cncf/soc/blob/master/README.md#project-ideas, which was used previously for the project ideas submissions, so nothing changed this time.

I am happy to create a new file for 2020 program specifically, whichever we prefer.

**Comment by idvoretskyi** [comment]
@smishra997 it's already there. If you are a project maintainer and plan to participate as a mentor, please submit your ideas as stated here - https://github.com/cncf/soc/blob/master/README.md#project-ideas

**Comment by caniszczyk** [comment]
We were accepted to GSOC, wohoo!

@idvoretskyi please do a final push to get project ideas from CNCF projects

**Comment by idvoretskyi** [comment]
> a final push to get project ideas from CNCF projects

Just sent out another reminder to the CNCF project maintainers - let's have them by EOW :)
